### ISSUE TITLE
Malformed UTF-8 characters, possibly incorrectly encoded when outputting as JSON

### ISSUE THREAD

**Issue by codepotato** [laratools/laratools#29]
Installing the package on a fresh install of L5.6 and hooking up to a new model. 

Creating a new instance of the model and outputting the new model as JSON via return $client or response()->json($client) throws an error about the binary uuid characters. 

Tried setting the UUID column to hidden on the model and then appending the uuid_text attribute but no joy.

Happy to provide more code to help fix zee bug @iWader.

**Comment by codepotato** [comment]
I imagine the trait needs to hide the UUID collumn when the model is being converted to JSON, but at present it doesn't. Trying to consider how this can be achieved within the trait, or whether it's something that needs manual intervention on the model.

**Comment by iWader** [comment]
> Tried setting the UUID column to hidden on the model and then appending the uuid_text attribute but no joy.

It handles this out of the box, when calling `toJson()` on the model (which laravel does in the background) it will replace the `uuid` attribute with `uuid_text` automatically.

Can you post your model code? Sounds like you're maybe using the `Uuid` trait, instead of `BinaryUuid`?

**Comment by codepotato** [comment]
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Laratools\Eloquent\BinaryUuid;

class Client extends Model
{
    //
    use BinaryUuid;

    //
    protected $fillable = [
        'name','total_invested','age','db_transfer','pension_transfer','vct_eis','cashflow_analysis','meeting_freq','annual_touch_points','clients_introduced','intro_total'
    ];

    protected $hidden = ['uuid'];

    protected $appends = ['uuid_text'];
}
```

**Comment by codepotato** [comment]
@iWader That was the last iteration of the model. However it wasn't working also when I removed the protected and appends attributes.

**Comment by iWader** [comment]
Can you post your stack trace? Just tested a vanilla install and working fine here.

**Comment by codepotato** [comment]
@iWader Can give you repo access if you like. Nothing sensitive in it at the moment.

**Comment by iWader** [comment]
You have a `QueryException` as one of your columns doesn't have a default value. Not a lot I can do to prevent it, at that point the binary is part of the query bindings.

Don't send the stack trace to the browser :+1:

**Comment by codepotato** [comment]
@iWader Ah, roger that. Will adjust. Appreciate the quick reply on this one and sorry to waste your time!
