### ISSUE TITLE
Request - A way to automatically use stringuuid in routes when using binaryuuids? 

### ISSUE THREAD

**Issue by codepotato** [laratools/laratools#35]
Afternoony, I'm using laratools on a project and wondered if there's a nice elegant way of using the binary uuids in the schema, but then automatically telling laravel's route system to use and look for the string uuid. 

Or will I need to transpose the uuid (string) being passed in through a route to the correct element? 

e.g. in a controller 

    public function getItem(ModelName $item){
        $item instanceOf ModelName; 
    }

At the moment I'm doing the following: 

    public function getItem($uuid){
        $item = ModelName::uuid($uuid)->first();
    }

**Comment by iWader** [comment]
There’s not a way to implement this out the box as part of laratools. I
wanted to do that but not possible as there’s not way to tell if it should
be searching for a binary uuid or not, unless you’re using primary keys,
but MySQL doesn’t support that. (Use Postgres, it has native uuid support
so you don’t need this hacky binary time-sorted stuff 👌)

You can achieve it by setting up your own route binding with Route::bind()

**Comment by codepotato** [comment]
Thanks for the super-quick response. So if we used the uuid as the primary key it would work because laravel instinctively uses the primary key in the route bind mechanism out-of-the-box?

**Comment by iWader** [comment]
Primary key only works if you use string uuids, which the performance is poor at best.

Your best option if you want to stick with MySQL is to use explicit route bindings https://laravel.com/docs/5.7/routing#explicit-binding

```php
Route::bind('user', function (string $uuid): ?User {
    return User::uuid($uuid)->first();
});

Route::get('/users/{user}', [UserController::class, 'get']);
```

Then in your controller

```php
public function get(User $user)
{
    //
}
```

**Comment by codepotato** [comment]
Hmm, taking your heed and using binaryuuid in my models as it's faster and more secure. Will use the manual work-around for now, but appreciate the really quick reply. 👍
