### ISSUE TITLE
Question - Can encrypted model elements be searched against?

### ISSUE THREAD

**Issue by codepotato** [laratools/laratools#36]
Hello again! 

Am I right in thinking that any column set as encrypted cannot be searched using query builder? I would have to retrieve all values and then foreach over to decrypt and read?

**Comment by iWader** [comment]
Yup, that's right.

It is possible though. Pros/Cons are explained in the article. https://paragonie.com/blog/2017/05/building-searchable-encrypted-databases-with-php-and-sql
