### ISSUE TITLE
Encryptable doesn't decrypt

### ISSUE THREAD

**Issue by codepotato** [laratools/laratools#43]
Me again! 

So, encrypted fine using the encryptable trait but it's not decrypting when it comes back out:

<img width="1004" alt="Screen Shot 2019-03-29 at 14 46 27" src="https://user-images.githubusercontent.com/417524/55240731-7917f880-5231-11e9-8ea4-ae16734db28d.png">

<img width="215" alt="Screen Shot 2019-03-29 at 14 47 05" src="https://user-images.githubusercontent.com/417524/55240761-8a610500-5231-11e9-8e79-2c36495cf68a.png">

Any ideas?

**Comment by iWader** [comment]
Try disabling safe decrypt and see why it's throwing

Add `protected $safeDecrypt = false;` to your model, should cause it to throw the exception when it fails to decrypt

**Comment by codepotato** [comment]
No errors thrown @iWader

**Comment by iWader** [comment]
Hmm I can only assume the trait isn't being called for some reason. Which version of Laravel is this?

**Comment by codepotato** [comment]
It's working on other models, which is why i'm really confused! It's working a treat on messages and other parts of the system but not on this one model. 🤔

**Comment by iWader** [comment]
Try this checklist, I know some stuff is super obvious but worth double checking

- [ ] Model uses the `Encryptable` trait
- [ ] You have a single `$casts` attribute on the model
- [ ] If you put an obviously wrong value in the attribute does it throw an error when you disable `$safeDecrypt`
- [ ] Add a log to the `Encryptable::isEncryptableAttribute()` method and ensure it's being called

**Comment by codepotato** [comment]
Done all of those and it's still not throwing errors and is running the encryptable process.

**Comment by iWader** [comment]
Did you get this resolved in the end?

**Comment by codepotato** [comment]
No, not really. Turned encryption off on the particular element. Weird.
